### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by omni-** [ArcanoxDragon/Mechterra#1]
I tried downloading your code and running it in VS2012 but it failed miserably with 57 errors. What IDE are you using?

**Comment by ArcanoxDragon** [comment]
You're going to want to use MinGW and Eclipse. The code isn't written for
MSVC.

**Comment by omni-** [comment]
Is there any way I could get it to work in MSVS?

**Comment by ArcanoxDragon** [comment]
Very unlikely. This isn't coded in Visual C++, it's coded in cross-platform C++. Visual Studio isn't going to be able to compile it correctly. Eclipse has more features anyways and it is free; I recommend just getting it.

**Comment by omni-** [comment]
Ok. I already have it because I also code in Java, but VS is my IDE of choice, so I was hoping there was a way. Thanks anyway,
